### ISSUE TITLE
Errors when trying to use this script.

### ISSUE THREAD

**Issue by gyoza** [yincrash/hubot-trivia-game#5]
When the bot comes online we issue

!trivia

you get this error the first time always. 

'''
[Mon Nov 10 2014 10:54:35 GMT-0800 (PST)] ERROR ReferenceError: robot is not defined
  at Game.askQuestion (/PATHANDSTUFF//hipbot/node_modules/hubot-trivia-game/src/trivia-game.coffee:42:7, <js>:26:9)
  at TextListener.callback (/PATHANDSTUFF//hipbot/node_modules/hubot-trivia-game/src/trivia-game.coffee:91:5, <js>:86:19)
  at TextListener.Listener.call (/PATHANDSTUFF//hipbot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/PATHANDSTUFF//hipbot/node_modules/hubot/src/robot.coffee:197:9, <js>:142:33)
  at HipChat.Adapter.receive (/PATHANDSTUFF//hipbot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at /PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/src/hipchat.js:206:24
  at invokeCallback (/PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:161:15)
  at Object.<anonymous> (/PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:193:9)
  at /PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:13:16
  at process._tickCallback (node.js:419:13)
'''

Second time you issue the command it works.

Attempting to answer with !a <answer> or !answer <answer> you get the following error

[Mon Nov 10 2014 10:54:50 GMT-0800 (PST)] ERROR TypeError: Cannot call method 'toLowerCase' of undefined
  at Game.answerQuestion (/PATHANDSTUFF//hipbot/node_modules/hubot-trivia-game/src/trivia-game.coffee:63:10, <js>:48:67)
  at TextListener.callback (/PATHANDSTUFF//hipbot/node_modules/hubot-trivia-game/src/trivia-game.coffee:97:5, <js>:92:19)
  at TextListener.Listener.call (/PATHANDSTUFF//hipbot/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/PATHANDSTUFF//hipbot/node_modules/hubot/src/robot.coffee:197:9, <js>:142:33)
  at HipChat.Adapter.receive (/PATHANDSTUFF//hipbot/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at /PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/src/hipchat.js:206:24
  at invokeCallback (/PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:161:15)
  at Object.<anonymous> (/PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:193:9)
  at /PATHANDSTUFF//hipbot/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:13:16
  at process._tickCallback (node.js:419:13)

Your help is appreciated as we really want trivia:P

**Comment by yincrash** [comment]
Okay. This should be fixed. I think I was writing against an older version of coffeescript that was more lenient with my syntax. Please try running `npm install hubot-trivia-game` again (1.0.2 should install) and let me know if it works!
